parameters:
  - name: WorkspaceName
    type: string
    displayName: Workspace Name (Environment)

trigger: none

pool:
  vmImage: windows-latest

variables:
  - template: ../Common.variables.yml
    parameters:
      WorkspaceName: ${{ parameters.WorkspaceName }}

steps:

  - checkout: self
    persistCredentials: True

  - task: PowerShell@2
    inputs:
      filePath: '$(Common.PipelinesFolder)/deploy/Ensure-PowerBIWorkspace.ps1'
      arguments: '-TenantId ''$(TenantId)'' -ClientId ''$(ClientId)'' -ClientSecret ''$(ClientSecret)'' -WorkspaceName ''${{ parameters.WorkspaceName }}'''
      pwsh: true
      showWarnings: true
    displayName: Ensure ${{ parameters.WorkspaceName }} workspace

  - task: PowerShell@2
    inputs:
      filePath: '$(Common.PipelinesFolder)/deploy/Import-PowerBIDatasets.ps1'
      arguments: '-TenantId ''$(TenantId)'' -ClientId ''$(ClientId)'' -ClientSecret ''$(ClientSecret)'' -WorkspaceName ''${{ parameters.WorkspaceName }}'' -BimFolderPath ''$(Common.BimFolderPath)'''
      showWarnings: true
    displayName: Import Datasets to ${{ parameters.WorkspaceName }}

  - powershell: choco install PowerBI -ignore-checksums
    displayName: Install PowerBI

  - task: PowerShell@2
    inputs:
      filePath: '$(Common.PipelinesFolder)/util/Install-PbiTools.ps1'
      arguments: '-PbiToolsPath ''$(Common.PbiToolsPath)'''
      pwsh: true
      showWarnings: true
    displayName: Download and Install PBI Tools

  - task: PowerShell@2
    inputs:
      filePath: '$(Common.PipelinesFolder)/deploy/Compile-PowerBIReports.ps1'
      arguments: '-PbiToolsPath ''$(Common.PbiToolsPath)'' -ReportSourceFolderPath ''$(Common.ReportSourceFolderPath)'' -pbixFolderPath ''$(Common.CompiledPbixFolderPath)'''
      pwsh: true
      showWarnings: true
    displayName: Compile PBIX Files

  - task: PowerShell@2
    inputs:
      filePath: '$(Common.PipelinesFolder)/deploy/Import-PowerBIReports.ps1'
      arguments: '-TenantId ''$(TenantId)'' -ClientId ''$(ClientId)'' -ClientSecret ''$(ClientSecret)'' -WorkspaceName ''${{ parameters.WorkspaceName }}'' -PbixFolderPath ''$(Common.CompiledPbixFolderPath)'''
      pwsh: true
      showWarnings: true
    displayName: Import Reports to ${{ parameters.WorkspaceName }}

  - task: PowerShell@2
    inputs:
      filePath: '$(Common.PipelinesFolder)/deploy/Update-ReportDatasets.ps1'
      arguments: '-TenantId ''$(TenantId)'' -ClientId ''$(ClientId)'' -ClientSecret ''$(ClientSecret)'' -WorkspaceName ''${{ parameters.WorkspaceName }}'''
      pwsh: true
      showWarnings: true
    displayName: Rebind report datasets and update credentials in ${{ parameters.WorkspaceName }}

  - publish: $(Common.CompiledPbixFolderPath)
    artifact: 'PBIX'
    condition: always()