parameters:
  - name: WorkspaceName
    type: string
    displayName: Workspace Name (Environment)

trigger: none

pool:
  vmImage: windows-latest

variables:
  - template: ../Common.variables.yml

steps:

  - checkout: self
    persistCredentials: True

  - task: PowerShell@2
    inputs:
      filePath: '$(Build.SourcesDirectory)/ci-cd/export/Export-PowerBIReports.ps1'
      arguments: '-TenantId ''$(TenantId)'' -ClientId ''$(ClientId)'' -ClientSecret ''$(ClientSecret)'' -WorkspaceName ''${{ parameters.WorkspaceName }}'' -PbixFolderPath ''$(Common.ExportedPbixFolderPath)'''
      showWarnings: true
    displayName: 'Export PBIX Files'

  - publish: $(Common.ExportedPbixFolderPath)
    artifact: 'PBIX'

  - powershell: choco install PowerBI -ignore-checksums
    displayName: Install PowerBI

  - task: PowerShell@2
    inputs:
      filePath: '$(Build.SourcesDirectory)/ci-cd/util/Install-PbiTools.ps1'
      arguments: '-PbiToolsPath ''$(Common.PbiToolsPath)'''
      showWarnings: true
    displayName: Download and Install PBI Tools
      
  - task: PowerShell@2
    inputs:
      filePath: '$(Build.SourcesDirectory)/ci-cd/export/Extract-PowerBIReports.ps1'
      arguments: '-PbiToolsPath ''$(Common.PbiToolsPath)'' -PbixFolderPath ''$(Common.ExportedPbixFolderPath)'' -ReportSourceFolderPath ''$(Common.ReportSourceFolderPath)'''
      showWarnings: true
    displayName: Extract PBIX Files

  - powershell: |
      cd $(Build.SourcesDirectory)

      git config user.email "export.pipeline@dev.azure.com"
      git config user.name "Export Pipeline"

      git fetch origin
      git checkout $(Common.SourceBranchName)
      git switch -c $(Common.WorkspaceExportBranchName)
      git branch -u origin/$(Common.WorkspaceExportBranchName)

      git pull

      git add --all
      git commit -m "${{ parameters.WorkspaceName }} $(Build.BuildId)"

      git push --set-upstream origin $(Common.WorkspaceExportBranchName)
    displayName: Commit Exported Workspace