parameters:
- name: ServiceConnection
  displayName: Service Connection
  type: string

trigger: none

pool:
  vmImage: windows-latest

variables:
  location: 'CanadaCentral'
  backendResourceGroupName: 'TerraForm'
  backendStorageAccountName: 'TFStatePbiDevOps'
  backendStorageAccountContainerName: 'TerraFormState'
  vmResourceGroupName: 'PbiDevOps'

steps:
- task: TerraformInstaller@0
  inputs:
    terraformVersion: 'latest'

- task: AzureCLI@2
  inputs:
    azureSubscription: '${{ parameters.ServiceConnection }}'
    scriptType: 'pscore'
    scriptLocation: 'scriptPath'
    scriptPath: 'Create-PowerBIPipelineAgents.ps1'
    arguments: '-AzdoUri "$(System.TeamFoundationCollectionUri)" -Location "$(location)" -BackendResourceGroupName "$(backendResourceGroupName)" -BackendStorageAccountName "$(backendStorageAccountName)" -BackendStorageContainerName "$(backendStorageAccountContainerName)" -VmResourceGroupName "$(vmResourceGroupName)"'
    failOnStandardError: true
  env:
    SYSTEM_ACCESSTOKEN: $(System.AccessToken)