parameters:
  - name: PbixFileUrl
    type: string
    displayName: Pbix File Url

trigger: none

pool: default

steps:
- checkout: none

- powershell: |
    $pbixFileUrl = '${{ parameters.PbixFileUrl }}'
    $fileName = Split-Path -Path $pbixFileUrl -Leaf
    $pbixDownloadPath = Join-Path '$(Build.BinariesDirectory)' -ChildPath $fileName
    Invoke-WebRequest -Uri $pbixFileUrl -OutFile $pbixDownloadPath

    $env:PBITOOLS_LogLevel = 'Verbose'
    C:\pbi-tools\pbi-tools.exe extract $pbixDownloadPath
  displayName: 'Download and Extract PBIX'

- publish: '$(Build.BinariesDirectory)'
  artifact: 'PBIX'