parameters:
  - name: PbixFileUrl
    type: string
    displayName: Pbix File Url

trigger: none

pool: default

steps:
- checkout: none

- powershell: Invoke-WebRequest -Uri '${{ parameters.PbixFileUrl }}' -OutFile '$(Build.BinariesDirectory)/sample.pbix'

- powershell: |
    cd '$(Build.ArtifactStagingDirectory)'
    C:\pbi-tools\pbi-tools.exe extract '$(Build.BinariesDirectory)\sample.pbix' -extractFolder '$(Build.ArtifactStagingDirectory)' -modelSerialization Raw
    ls '$(Build.ArtifactStagingDirectory)'
  displayName: 'Extract PBIX'

- publish: '$(Build.ArtifactStagingDirectory)'
  artifact: 'sample.pbix'