parameters:
  - name: PbixFileUrl
    type: string
    displayName: Pbix File Url

trigger: none

pool: default

steps:
- checkout: none

- powershell: |
    $pbixFileUrl = '${{ parameters.PbixFileUrl }}'
    $fileName = [System.Web.HttpUtility]::UrlDecode((Split-Path -Path $pbixFileUrl -Leaf).Split('?')[0])
    $pbixDownloadPath = Join-Path '$(Build.BinariesDirectory)' -ChildPath $fileName

    echo "Downloading $pbixFileUrl to $pbixDownloadPath"
    Invoke-WebRequest -Uri $pbixFileUrl -OutFile $pbixDownloadPath

    $env:PBITOOLS_LogLevel = 'Verbose'
    echo "Extracting $pbixDownloadPath"
    C:\pbi-tools\pbi-tools.exe extract $pbixDownloadPath
  displayName: 'Download and Extract PBIX'

- publish: '$(Build.BinariesDirectory)'
  artifact: 'PBIX'