parameters:
  - name: PbixFileUrl
    type: string
    displayName: Pbix File Url

trigger: none

pool: default

steps:
- checkout: none

- powershell: Invoke-WebRequest -Uri '${{ parameters.PbixFileUrl }}' -OutFile '$(Build.BinariesDirectory)/sample.pbix'

- powershell: C:\pbi-tools\pbi-tools.exe extract '$(Build.BinariesDirectory)/sample.pbix' -extractFolder '$(Build.ArtifactStagingDirectory)' -modelSerialization Raw
  displayName: 'Test Power BI Tools'

- publish: '$(Build.ArtifactStagingDirectory)'
  artifact: 'sample.pbix'