---
- hosts: azurevms
  gather_facts: no
  tasks:
  - name: Install chocolatey
    win_chocolatey:
      name:
      - chocolatey
      - chocolatey-core.extension
      state: present

  - name: Install Power BI
    win_chocolatey:
      name: PowerBI
      state: present
      ignore_checksums: yes

  - name: Install Azure Pipelines Agent
    win_chocolatey:
      name: azure-pipelines-agent
      state: present

  - name: Install Azure CLI
    win_chocolatey:
      name: azure-cli
      state: present
        
  - name: Configure Azure Pipelines Agent
    ansible.windows.win_powershell:
      script: |
        [CmdletBinding()]
        param (
          [string]$AgentInstallPath,
          [string]$AgentName,
          [string]$PoolName,
          [string]$AzdoUri,
          [string]$AzdoPat,
          [string]$RunAsAutoLogon,
          [string]$WindowsLogonAccount,
          [string]$WindowsLogonPassword,
          [string]$WorkDirectory
        )

        if (-not $AgentInstallPath) {
          $AgentInstallPath = 'C:\agent'
        }

        $AgentName = $env:ComputerName

        try {
          Push-Location -Path $AgentInstallPath
          
          Remove-Item "$AgentInstallPath\_diag\*" -Recurse -Force -ErrorAction SilentlyContinue

          $agentConfigCmd = "cmd.exe /C .\config.cmd --unattended --url '$AzdoUri' --auth 'pat' --token '$AzdoPat' --pool '$PoolName' --agent '$AgentName' --runAsService --windowsLogonAccount '$WindowsLogonAccount' --windowsLogonPassword '$WindowsLogonPassword'"
          Invoke-Expression -Command $agentConfigCmd
        } finally {
          Pop-Location
        }
      parameters:
        PoolName: '{{ PoolName }}'
        AzdoUri: '{{ AzdoUri }}'
        AzdoPat: '{{ AzdoPat }}'
        WindowsLogonAccount: '{{ WindowsLogonAccount }}'
        WindowsLogonPassword: '{{ WindowsLogonPassword }}'
    register: pwsh_output
        
  - name: Output Azure Pipelines Agent Configuration Log Paths
    ansible.windows.win_powershell:
      script: |
        $logFiles = Get-ChildItem "C:\agent\_diag\*.log"
        echo ($logFiles).FullName
    register: log_path
        
  - name: Fetch Azure Pipelines Agent Configuration Logs
    ansible.builtin.fetch:
      src: "{{ log_path.output[0] }}"
      dest: "{{ inventory_hostname }}.log"
      flat: yes
    when: log_path.output[0] != None
        
  - name: Output Azure Pipelines Agent Configuration Log Paths
    ansible.windows.win_powershell:
      script: |
        $logFiles = Get-ChildItem "C:\agent\_diag\*.log"
        echo ($logFiles).FullName
    register: log_path

  - name: Install pbi-tools
    ansible.windows.win_powershell:
      script: |
        $pbiToolsPath = 'C:\pbi-tools'
        $mkdirResult = mkdir $pbiToolsPath -Force

        try {
            pushd $pbiToolsPath
            $pbiToolsUrl = "https://api.github.com/repos/action-bi-toolkit/pbi-tools/releases/latest"
            
            $response = Invoke-WebRequest $pbiToolsUrl -UseBasicParsing
            $content = $response.Content | ConvertFrom-Json
            
            $assetResponse = Invoke-WebRequest $content.assets_url -UseBasicParsing
            $assetContent = $assetResponse.Content | ConvertFrom-Json
            
            $fileName = Split-Path -Path $assetContent.browser_download_url[0] -Leaf

            $downloadZipFile = Join-Path $pbiToolsPath -ChildPath $fileName
            $downloadResponse = Invoke-WebRequest $assetContent.browser_download_url[0] -OutFile $downloadZipFile -UseBasicParsing
            
            $expandResult = Expand-Archive $downloadZipFile -DestinationPath $pbiToolsPath -Force
            
            $pbiToolsCmdPath = Join-Path $pbiToolsPath -ChildPath 'pbi-tools.exe'
            $env:Path += ";$pbiToolsPath"
        }
        finally {
            popd
        }

  - name: Restart
    ansible.windows.win_powershell:
      script: Restart-Computer