parameters:
  - name: WorkspaceName
    type: string
    displayName: Workspace Name (Environment)

trigger: none

pool:
  vmImage: windows-latest

variables:
  - group: PowerBI
  - name: PbixFolderPath
    value: '$(Build.BinariesDirectory)/pbix'
  - name: ReportSourceFolderPath
    value: '$(Build.SourcesDirectory)/src/'
  - name: Common.SolutionExportBranchName
    value: 'workspace-${{ parameters.WorkspaceName }}-export-$(Build.BuildId)'
  - name: Common.SourceBranchName
    value: $[ replace('$(Build.SourceBranch)', 'refs/heads/', '') ]

steps:

  - checkout: self
    persistCredentials: True

  - task: PowerShell@2
    inputs:
      filePath: '$(Build.SourcesDirectory)/ci-cd/Export-PowerBIReports.ps1'
      arguments: '-TenantId ''$(TenantId)'' -ClientId ''$(ClientId)'' -ClientSecret ''$(ClientSecret)'' -WorkspaceName ''${{ parameters.WorkspaceName }}'' -PbixFolderPath ''$(PbixFolderPath)'''
      showWarnings: true
    displayName: 'Export PBIX Files'

  - publish: $(PbixFolderPath)
    artifact: 'PBIX'

  - powershell: choco install PowerBI
    displayName: Install PowerBI

  - powershell: |
      $pbiToolsPath = '$(Agent.ToolsDirectory)\pbi-tools'
      $mkdirResult = mkdir $pbiToolsPath -Force

      try {
          pushd $pbiToolsPath
          $pbiToolsUrl = "https://api.github.com/repos/action-bi-toolkit/pbi-tools/releases/latest"
          
          $response = Invoke-WebRequest $pbiToolsUrl -UseBasicParsing
          $content = $response.Content | ConvertFrom-Json
          
          $assetResponse = Invoke-WebRequest $content.assets_url -UseBasicParsing
          $assetContent = $assetResponse.Content | ConvertFrom-Json
          
          $fileName = Split-Path -Path $assetContent.browser_download_url[0] -Leaf

          $downloadZipFile = Join-Path $pbiToolsPath -ChildPath $fileName
          $downloadResponse = Invoke-WebRequest $assetContent.browser_download_url[0] -OutFile $downloadZipFile -UseBasicParsing
          
          $expandResult = Expand-Archive $downloadZipFile -DestinationPath $pbiToolsPath -Force
          
          $pbiToolsCmdPath = Join-Path $pbiToolsPath -ChildPath 'pbi-tools.exe'
          $env:Path += ";$pbiToolsPath"
          $env:PBITOOLS_LogLevel = 'Verbose'
      }
      finally {
          popd
      }
    displayName: Download and Install PBI Tools

  - powershell: |
      $pbixFolderPath = '$(PbixFolderPath)'
      $reportSourceFolderPath = '$(ReportSourceFolderPath)'
      New-Item -ItemType "directory" -Path $reportSourceFolderPath -Force

      $pbiToolsPath = '$(Agent.ToolsDirectory)\pbi-tools'
      $env:Path += ";$pbiToolsPath"
      $pbiToolsCmdPath = Join-Path $pbiToolsPath -ChildPath 'pbi-tools.exe'
      echo "pbi-tools command path $pbiToolsCmdPath"

      $env:PBITOOLS_LogLevel = 'Verbose'

      $reportFiles = Get-ChildItem -Path $pbixFolderPath -Recurse -Filter *.pbix

      foreach ($reportFile in $reportFiles) {
          echo "Extracting $($reportFile.FullName)"
          pbi-tools extract $reportFile.FullName
      }
      gci -Path $pbixFolderPath -Directory | % { Move-Item $_ '$(Build.SourcesDirectory)' }
    displayName: Extract PBIX Files

  - powershell: |
      cd $(Build.SourcesDirectory)

      git config user.email "export.pipeline@dev.azure.com"
      git config user.name "Export Pipeline"

      git fetch origin
      git checkout $(Common.SourceBranchName)
      git switch -c $(Common.SolutionExportBranchName)
      git branch -u origin/$(Common.SolutionExportBranchName)

      git pull

      git add --all
      git commit -m "${{ parameters.WorkspaceName }} $(Build.BuildId)"

      git push --set-upstream origin $(Common.SolutionExportBranchName)
    displayName: Commit Exported Solution(s)